// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/cplpbv1/control-plane.proto

package cplpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_TCP         Protocol = 1
	Protocol_PROTOCOL_UDP         Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cplpbv1_control_plane_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_api_proto_cplpbv1_control_plane_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{0}
}

// Статус dpl
type DataPlaneHealth int32

const (
	DataPlaneHealth_HEALTH_UNKNOWN   DataPlaneHealth = 0
	DataPlaneHealth_HEALTH_HEALTHY   DataPlaneHealth = 1
	DataPlaneHealth_HEALTH_UNHEALTHY DataPlaneHealth = 2
	DataPlaneHealth_HEALTH_DRAINING  DataPlaneHealth = 3
)

// Enum value maps for DataPlaneHealth.
var (
	DataPlaneHealth_name = map[int32]string{
		0: "HEALTH_UNKNOWN",
		1: "HEALTH_HEALTHY",
		2: "HEALTH_UNHEALTHY",
		3: "HEALTH_DRAINING",
	}
	DataPlaneHealth_value = map[string]int32{
		"HEALTH_UNKNOWN":   0,
		"HEALTH_HEALTHY":   1,
		"HEALTH_UNHEALTHY": 2,
		"HEALTH_DRAINING":  3,
	}
)

func (x DataPlaneHealth) Enum() *DataPlaneHealth {
	p := new(DataPlaneHealth)
	*p = x
	return p
}

func (x DataPlaneHealth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataPlaneHealth) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cplpbv1_control_plane_proto_enumTypes[1].Descriptor()
}

func (DataPlaneHealth) Type() protoreflect.EnumType {
	return &file_api_proto_cplpbv1_control_plane_proto_enumTypes[1]
}

func (x DataPlaneHealth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataPlaneHealth.Descriptor instead.
func (DataPlaneHealth) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{1}
}

// Use case response code for transparency
type ResponseCode int32

const (
	ResponseCode_RESPONSE_CODE_UNSPECIFIED    ResponseCode = 0
	ResponseCode_RESPONSE_CODE_HAS_CHANGES    ResponseCode = 1
	ResponseCode_RESPONSE_CODE_NO_CHANGES     ResponseCode = 2
	ResponseCode_RESPONSE_CODE_CLIENT_AHEAD   ResponseCode = 3
	ResponseCode_RESPONSE_CODE_INTERNAL_ERROR ResponseCode = 4
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "RESPONSE_CODE_UNSPECIFIED",
		1: "RESPONSE_CODE_HAS_CHANGES",
		2: "RESPONSE_CODE_NO_CHANGES",
		3: "RESPONSE_CODE_CLIENT_AHEAD",
		4: "RESPONSE_CODE_INTERNAL_ERROR",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSE_CODE_UNSPECIFIED":    0,
		"RESPONSE_CODE_HAS_CHANGES":    1,
		"RESPONSE_CODE_NO_CHANGES":     2,
		"RESPONSE_CODE_CLIENT_AHEAD":   3,
		"RESPONSE_CODE_INTERNAL_ERROR": 4,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cplpbv1_control_plane_proto_enumTypes[2].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_api_proto_cplpbv1_control_plane_proto_enumTypes[2]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{2}
}

type EndpointOperationType int32

const (
	EndpointOperationType_ENDPOINT_OPERATION_TYPE_UNSPECIFIED EndpointOperationType = 0
	EndpointOperationType_ENDPOINT_OPERATION_TYPE_ADD         EndpointOperationType = 1
	EndpointOperationType_ENDPOINT_OPERATION_TYPE_REMOVE      EndpointOperationType = 2
	EndpointOperationType_ENDPOINT_OPERATION_TYPE_UPDATE      EndpointOperationType = 3
)

// Enum value maps for EndpointOperationType.
var (
	EndpointOperationType_name = map[int32]string{
		0: "ENDPOINT_OPERATION_TYPE_UNSPECIFIED",
		1: "ENDPOINT_OPERATION_TYPE_ADD",
		2: "ENDPOINT_OPERATION_TYPE_REMOVE",
		3: "ENDPOINT_OPERATION_TYPE_UPDATE",
	}
	EndpointOperationType_value = map[string]int32{
		"ENDPOINT_OPERATION_TYPE_UNSPECIFIED": 0,
		"ENDPOINT_OPERATION_TYPE_ADD":         1,
		"ENDPOINT_OPERATION_TYPE_REMOVE":      2,
		"ENDPOINT_OPERATION_TYPE_UPDATE":      3,
	}
)

func (x EndpointOperationType) Enum() *EndpointOperationType {
	p := new(EndpointOperationType)
	*p = x
	return p
}

func (x EndpointOperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointOperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cplpbv1_control_plane_proto_enumTypes[3].Descriptor()
}

func (EndpointOperationType) Type() protoreflect.EnumType {
	return &file_api_proto_cplpbv1_control_plane_proto_enumTypes[3]
}

func (x EndpointOperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointOperationType.Descriptor instead.
func (EndpointOperationType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{3}
}

type TargetGroupID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetGroupID) Reset() {
	*x = TargetGroupID{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGroupID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGroupID) ProtoMessage() {}

func (x *TargetGroupID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGroupID.ProtoReflect.Descriptor instead.
func (*TargetGroupID) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *TargetGroupID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DataPlaneID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPlaneID) Reset() {
	*x = DataPlaneID{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPlaneID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPlaneID) ProtoMessage() {}

func (x *DataPlaneID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPlaneID.ProtoReflect.Descriptor instead.
func (*DataPlaneID) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *DataPlaneID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Long-polling запрос от агента data-plane ноды
type DataPlaneAssignmentRequest struct {
	state              protoimpl.MessageState        `protogen:"open.v1"`
	NodeId             *DataPlaneID                  `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PlacementVersion   uint64                        `protobuf:"varint,2,opt,name=placement_version,json=placementVersion,proto3" json:"placement_version,omitempty"`
	TargetGroupsStatus map[string]*TargetGroupStatus `protobuf:"bytes,3,rep,name=target_groups_status,json=targetGroupsStatus,proto3" json:"target_groups_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WaitTimeoutSeconds uint32                        `protobuf:"varint,4,opt,name=wait_timeout_seconds,json=waitTimeoutSeconds,proto3" json:"wait_timeout_seconds,omitempty"`
	RequestId          string                        `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DataPlaneAssignmentRequest) Reset() {
	*x = DataPlaneAssignmentRequest{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPlaneAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPlaneAssignmentRequest) ProtoMessage() {}

func (x *DataPlaneAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPlaneAssignmentRequest.ProtoReflect.Descriptor instead.
func (*DataPlaneAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *DataPlaneAssignmentRequest) GetNodeId() *DataPlaneID {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *DataPlaneAssignmentRequest) GetPlacementVersion() uint64 {
	if x != nil {
		return x.PlacementVersion
	}
	return 0
}

func (x *DataPlaneAssignmentRequest) GetTargetGroupsStatus() map[string]*TargetGroupStatus {
	if x != nil {
		return x.TargetGroupsStatus
	}
	return nil
}

func (x *DataPlaneAssignmentRequest) GetWaitTimeoutSeconds() uint32 {
	if x != nil {
		return x.WaitTimeoutSeconds
	}
	return 0
}

func (x *DataPlaneAssignmentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Status of target group in dpl
type TargetGroupStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SpecVersion          uint64                 `protobuf:"varint,1,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	EndpointsVersion     uint64                 `protobuf:"varint,2,opt,name=endpoints_version,json=endpointsVersion,proto3" json:"endpoints_version,omitempty"`
	LastAppliedTimestamp int64                  `protobuf:"varint,3,opt,name=last_applied_timestamp,json=lastAppliedTimestamp,proto3" json:"last_applied_timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TargetGroupStatus) Reset() {
	*x = TargetGroupStatus{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGroupStatus) ProtoMessage() {}

func (x *TargetGroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGroupStatus.ProtoReflect.Descriptor instead.
func (*TargetGroupStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *TargetGroupStatus) GetSpecVersion() uint64 {
	if x != nil {
		return x.SpecVersion
	}
	return 0
}

func (x *TargetGroupStatus) GetEndpointsVersion() uint64 {
	if x != nil {
		return x.EndpointsVersion
	}
	return 0
}

func (x *TargetGroupStatus) GetLastAppliedTimestamp() int64 {
	if x != nil {
		return x.LastAppliedTimestamp
	}
	return 0
}

// Long polling changes
type DataPlaneAssignmentResponse struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	PlacementVersion uint64                   `protobuf:"varint,1,opt,name=placement_version,json=placementVersion,proto3" json:"placement_version,omitempty"`
	Added            []*TargetGroupAssignment `protobuf:"bytes,2,rep,name=added,proto3" json:"added,omitempty"`
	Updated          []*TargetGroupAssignment `protobuf:"bytes,3,rep,name=updated,proto3" json:"updated,omitempty"`
	Removed          []*TargetGroupID         `protobuf:"bytes,4,rep,name=removed,proto3" json:"removed,omitempty"`
	HasMore          bool                     `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	ServerTimestamp  int64                    `protobuf:"varint,6,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	ResponseCode     ResponseCode             `protobuf:"varint,7,opt,name=response_code,json=responseCode,proto3,enum=cplpbv1.ResponseCode" json:"response_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DataPlaneAssignmentResponse) Reset() {
	*x = DataPlaneAssignmentResponse{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPlaneAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPlaneAssignmentResponse) ProtoMessage() {}

func (x *DataPlaneAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPlaneAssignmentResponse.ProtoReflect.Descriptor instead.
func (*DataPlaneAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *DataPlaneAssignmentResponse) GetPlacementVersion() uint64 {
	if x != nil {
		return x.PlacementVersion
	}
	return 0
}

func (x *DataPlaneAssignmentResponse) GetAdded() []*TargetGroupAssignment {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *DataPlaneAssignmentResponse) GetUpdated() []*TargetGroupAssignment {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *DataPlaneAssignmentResponse) GetRemoved() []*TargetGroupID {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *DataPlaneAssignmentResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *DataPlaneAssignmentResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *DataPlaneAssignmentResponse) GetResponseCode() ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return ResponseCode_RESPONSE_CODE_UNSPECIFIED
}

type TargetGroupAssignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *TargetGroupID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// nullable
	Spec             *TargetGroupSpec          `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	SpecVersion      uint64                    `protobuf:"varint,3,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	Snapshot         *EndpointsSnapshot        `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Changelog        []*EndpointChangelogEntry `protobuf:"bytes,5,rep,name=changelog,proto3" json:"changelog,omitempty"`
	EndpointsVersion uint64                    `protobuf:"varint,6,opt,name=endpoints_version,json=endpointsVersion,proto3" json:"endpoints_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TargetGroupAssignment) Reset() {
	*x = TargetGroupAssignment{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGroupAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGroupAssignment) ProtoMessage() {}

func (x *TargetGroupAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGroupAssignment.ProtoReflect.Descriptor instead.
func (*TargetGroupAssignment) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *TargetGroupAssignment) GetId() *TargetGroupID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TargetGroupAssignment) GetSpec() *TargetGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *TargetGroupAssignment) GetSpecVersion() uint64 {
	if x != nil {
		return x.SpecVersion
	}
	return 0
}

func (x *TargetGroupAssignment) GetSnapshot() *EndpointsSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *TargetGroupAssignment) GetChangelog() []*EndpointChangelogEntry {
	if x != nil {
		return x.Changelog
	}
	return nil
}

func (x *TargetGroupAssignment) GetEndpointsVersion() uint64 {
	if x != nil {
		return x.EndpointsVersion
	}
	return 0
}

// Endpoints snapshot
type EndpointsSnapshot struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Endpoints []*Endpoint            `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// format: "sha256:<hex>"
	Checksum      string `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	TotalCount    uint32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointsSnapshot) Reset() {
	*x = EndpointsSnapshot{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointsSnapshot) ProtoMessage() {}

func (x *EndpointsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointsSnapshot.ProtoReflect.Descriptor instead.
func (*EndpointsSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *EndpointsSnapshot) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *EndpointsSnapshot) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *EndpointsSnapshot) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type EndpointChangelogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *Endpoint              `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointChangelogEntry) Reset() {
	*x = EndpointChangelogEntry{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointChangelogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointChangelogEntry) ProtoMessage() {}

func (x *EndpointChangelogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointChangelogEntry.ProtoReflect.Descriptor instead.
func (*EndpointChangelogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *EndpointChangelogEntry) GetSpec() *Endpoint {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *EndpointChangelogEntry) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Weight        uint32                 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *Endpoint) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Endpoint) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type UpsertTargetGroupSpecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *TargetGroupID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec           *TargetGroupSpec       `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertTargetGroupSpecRequest) Reset() {
	*x = UpsertTargetGroupSpecRequest{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTargetGroupSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTargetGroupSpecRequest) ProtoMessage() {}

func (x *UpsertTargetGroupSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTargetGroupSpecRequest.ProtoReflect.Descriptor instead.
func (*UpsertTargetGroupSpecRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertTargetGroupSpecRequest) GetId() *TargetGroupID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpsertTargetGroupSpecRequest) GetSpec() *TargetGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *UpsertTargetGroupSpecRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type TargetGroupSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=cplpbv1.Protocol" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	VirtualIp     string                 `protobuf:"bytes,3,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetGroupSpec) Reset() {
	*x = TargetGroupSpec{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGroupSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGroupSpec) ProtoMessage() {}

func (x *TargetGroupSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGroupSpec.ProtoReflect.Descriptor instead.
func (*TargetGroupSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{10}
}

func (x *TargetGroupSpec) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *TargetGroupSpec) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TargetGroupSpec) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

// Healthcheck config
type HealthCheckConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO:
	IntervalSeconds    uint32 `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TimeoutSeconds     uint32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	UnhealthyThreshold uint32 `protobuf:"varint,3,opt,name=unhealthy_threshold,json=unhealthyThreshold,proto3" json:"unhealthy_threshold,omitempty"`
	HealthyThreshold   uint32 `protobuf:"varint,4,opt,name=healthy_threshold,json=healthyThreshold,proto3" json:"healthy_threshold,omitempty"`
	Type               string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Path               string `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheckConfig) Reset() {
	*x = HealthCheckConfig{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckConfig) ProtoMessage() {}

func (x *HealthCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckConfig.ProtoReflect.Descriptor instead.
func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckConfig) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheckConfig) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheckConfig) GetUnhealthyThreshold() uint32 {
	if x != nil {
		return x.UnhealthyThreshold
	}
	return 0
}

func (x *HealthCheckConfig) GetHealthyThreshold() uint32 {
	if x != nil {
		return x.HealthyThreshold
	}
	return 0
}

func (x *HealthCheckConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthCheckConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UpsertTargetGroupSpecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *TargetGroupID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTargetGroupSpecResponse) Reset() {
	*x = UpsertTargetGroupSpecResponse{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTargetGroupSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTargetGroupSpecResponse) ProtoMessage() {}

func (x *UpsertTargetGroupSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTargetGroupSpecResponse.ProtoReflect.Descriptor instead.
func (*UpsertTargetGroupSpecResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertTargetGroupSpecResponse) GetId() *TargetGroupID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpsertTargetGroupSpecResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpsertTargetGroupSpecResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *UpsertTargetGroupSpecResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UpsertEndpointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetGroupId  *TargetGroupID         `protobuf:"bytes,1,opt,name=target_group_id,json=targetGroupId,proto3" json:"target_group_id,omitempty"`
	Endpoint       *Endpoint              `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Operation      EndpointOperationType  `protobuf:"varint,3,opt,name=operation,proto3,enum=cplpbv1.EndpointOperationType" json:"operation,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertEndpointRequest) Reset() {
	*x = UpsertEndpointRequest{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEndpointRequest) ProtoMessage() {}

func (x *UpsertEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEndpointRequest.ProtoReflect.Descriptor instead.
func (*UpsertEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertEndpointRequest) GetTargetGroupId() *TargetGroupID {
	if x != nil {
		return x.TargetGroupId
	}
	return nil
}

func (x *UpsertEndpointRequest) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *UpsertEndpointRequest) GetOperation() EndpointOperationType {
	if x != nil {
		return x.Operation
	}
	return EndpointOperationType_ENDPOINT_OPERATION_TYPE_UNSPECIFIED
}

func (x *UpsertEndpointRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UpsertEndpointResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetGroupId    *TargetGroupID         `protobuf:"bytes,1,opt,name=target_group_id,json=targetGroupId,proto3" json:"target_group_id,omitempty"`
	Endpoint         *Endpoint              `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	EndpointsVersion uint64                 `protobuf:"varint,3,opt,name=endpoints_version,json=endpointsVersion,proto3" json:"endpoints_version,omitempty"`
	Affected         bool                   `protobuf:"varint,4,opt,name=affected,proto3" json:"affected,omitempty"`
	Timestamp        int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpsertEndpointResponse) Reset() {
	*x = UpsertEndpointResponse{}
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEndpointResponse) ProtoMessage() {}

func (x *UpsertEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cplpbv1_control_plane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEndpointResponse.ProtoReflect.Descriptor instead.
func (*UpsertEndpointResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP(), []int{14}
}

func (x *UpsertEndpointResponse) GetTargetGroupId() *TargetGroupID {
	if x != nil {
		return x.TargetGroupId
	}
	return nil
}

func (x *UpsertEndpointResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *UpsertEndpointResponse) GetEndpointsVersion() uint64 {
	if x != nil {
		return x.EndpointsVersion
	}
	return 0
}

func (x *UpsertEndpointResponse) GetAffected() bool {
	if x != nil {
		return x.Affected
	}
	return false
}

func (x *UpsertEndpointResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_cplpbv1_control_plane_proto protoreflect.FileDescriptor

const file_api_proto_cplpbv1_control_plane_proto_rawDesc = "" +
	"\n" +
	"%api/proto/cplpbv1/control-plane.proto\x12\acplpbv1\x1a\x1fgoogle/protobuf/timestamp.proto\"%\n" +
	"\rTargetGroupID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"#\n" +
	"\vDataPlaneID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x9b\x03\n" +
	"\x1aDataPlaneAssignmentRequest\x12-\n" +
	"\anode_id\x18\x01 \x01(\v2\x14.cplpbv1.DataPlaneIDR\x06nodeId\x12+\n" +
	"\x11placement_version\x18\x02 \x01(\x04R\x10placementVersion\x12m\n" +
	"\x14target_groups_status\x18\x03 \x03(\v2;.cplpbv1.DataPlaneAssignmentRequest.TargetGroupsStatusEntryR\x12targetGroupsStatus\x120\n" +
	"\x14wait_timeout_seconds\x18\x04 \x01(\rR\x12waitTimeoutSeconds\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x1aa\n" +
	"\x17TargetGroupsStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.cplpbv1.TargetGroupStatusR\x05value:\x028\x01\"\x99\x01\n" +
	"\x11TargetGroupStatus\x12!\n" +
	"\fspec_version\x18\x01 \x01(\x04R\vspecVersion\x12+\n" +
	"\x11endpoints_version\x18\x02 \x01(\x04R\x10endpointsVersion\x124\n" +
	"\x16last_applied_timestamp\x18\x03 \x01(\x03R\x14lastAppliedTimestamp\"\xee\x02\n" +
	"\x1bDataPlaneAssignmentResponse\x12+\n" +
	"\x11placement_version\x18\x01 \x01(\x04R\x10placementVersion\x124\n" +
	"\x05added\x18\x02 \x03(\v2\x1e.cplpbv1.TargetGroupAssignmentR\x05added\x128\n" +
	"\aupdated\x18\x03 \x03(\v2\x1e.cplpbv1.TargetGroupAssignmentR\aupdated\x120\n" +
	"\aremoved\x18\x04 \x03(\v2\x16.cplpbv1.TargetGroupIDR\aremoved\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\x12)\n" +
	"\x10server_timestamp\x18\x06 \x01(\x03R\x0fserverTimestamp\x12:\n" +
	"\rresponse_code\x18\a \x01(\x0e2\x15.cplpbv1.ResponseCodeR\fresponseCode\"\xb4\x02\n" +
	"\x15TargetGroupAssignment\x12&\n" +
	"\x02id\x18\x01 \x01(\v2\x16.cplpbv1.TargetGroupIDR\x02id\x12,\n" +
	"\x04spec\x18\x02 \x01(\v2\x18.cplpbv1.TargetGroupSpecR\x04spec\x12!\n" +
	"\fspec_version\x18\x03 \x01(\x04R\vspecVersion\x126\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x1a.cplpbv1.EndpointsSnapshotR\bsnapshot\x12=\n" +
	"\tchangelog\x18\x05 \x03(\v2\x1f.cplpbv1.EndpointChangelogEntryR\tchangelog\x12+\n" +
	"\x11endpoints_version\x18\x06 \x01(\x04R\x10endpointsVersion\"\x81\x01\n" +
	"\x11EndpointsSnapshot\x12/\n" +
	"\tendpoints\x18\x01 \x03(\v2\x11.cplpbv1.EndpointR\tendpoints\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\rR\n" +
	"totalCount\"Y\n" +
	"\x16EndpointChangelogEntry\x12%\n" +
	"\x04spec\x18\x01 \x01(\v2\x11.cplpbv1.EndpointR\x04spec\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"F\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weight\"\x9d\x01\n" +
	"\x1cUpsertTargetGroupSpecRequest\x12&\n" +
	"\x02id\x18\x01 \x01(\v2\x16.cplpbv1.TargetGroupIDR\x02id\x12,\n" +
	"\x04spec\x18\x02 \x01(\v2\x18.cplpbv1.TargetGroupSpecR\x04spec\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"s\n" +
	"\x0fTargetGroupSpec\x12-\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x11.cplpbv1.ProtocolR\bprotocol\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x03 \x01(\tR\tvirtualIp\"\xed\x01\n" +
	"\x11HealthCheckConfig\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\rR\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\x12/\n" +
	"\x13unhealthy_threshold\x18\x03 \x01(\rR\x12unhealthyThreshold\x12+\n" +
	"\x11healthy_threshold\x18\x04 \x01(\rR\x10healthyThreshold\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\"\x99\x01\n" +
	"\x1dUpsertTargetGroupSpecResponse\x12&\n" +
	"\x02id\x18\x01 \x01(\v2\x16.cplpbv1.TargetGroupIDR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xed\x01\n" +
	"\x15UpsertEndpointRequest\x12>\n" +
	"\x0ftarget_group_id\x18\x01 \x01(\v2\x16.cplpbv1.TargetGroupIDR\rtargetGroupId\x12-\n" +
	"\bendpoint\x18\x02 \x01(\v2\x11.cplpbv1.EndpointR\bendpoint\x12<\n" +
	"\toperation\x18\x03 \x01(\x0e2\x1e.cplpbv1.EndpointOperationTypeR\toperation\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\xee\x01\n" +
	"\x16UpsertEndpointResponse\x12>\n" +
	"\x0ftarget_group_id\x18\x01 \x01(\v2\x16.cplpbv1.TargetGroupIDR\rtargetGroupId\x12-\n" +
	"\bendpoint\x18\x02 \x01(\v2\x11.cplpbv1.EndpointR\bendpoint\x12+\n" +
	"\x11endpoints_version\x18\x03 \x01(\x04R\x10endpointsVersion\x12\x1a\n" +
	"\baffected\x18\x04 \x01(\bR\baffected\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp*H\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x02*d\n" +
	"\x0fDataPlaneHealth\x12\x12\n" +
	"\x0eHEALTH_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x01\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x02\x12\x13\n" +
	"\x0fHEALTH_DRAINING\x10\x03*\xac\x01\n" +
	"\fResponseCode\x12\x1d\n" +
	"\x19RESPONSE_CODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RESPONSE_CODE_HAS_CHANGES\x10\x01\x12\x1c\n" +
	"\x18RESPONSE_CODE_NO_CHANGES\x10\x02\x12\x1e\n" +
	"\x1aRESPONSE_CODE_CLIENT_AHEAD\x10\x03\x12 \n" +
	"\x1cRESPONSE_CODE_INTERNAL_ERROR\x10\x04*\xa9\x01\n" +
	"\x15EndpointOperationType\x12'\n" +
	"#ENDPOINT_OPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bENDPOINT_OPERATION_TYPE_ADD\x10\x01\x12\"\n" +
	"\x1eENDPOINT_OPERATION_TYPE_REMOVE\x10\x02\x12\"\n" +
	"\x1eENDPOINT_OPERATION_TYPE_UPDATE\x10\x032\xca\x02\n" +
	"\x13ControlPlaneService\x12n\n" +
	"\x1aStreamDataPlaneAssignments\x12#.cplpbv1.DataPlaneAssignmentRequest\x1a$.cplpbv1.DataPlaneAssignmentResponse\"\x03\x90\x02\x010\x01\x12k\n" +
	"\x15UpsertTargetGroupSpec\x12%.cplpbv1.UpsertTargetGroupSpecRequest\x1a&.cplpbv1.UpsertTargetGroupSpecResponse\"\x03\x90\x02\x02\x12V\n" +
	"\x0eUpsertEndpoint\x12\x1e.cplpbv1.UpsertEndpointRequest\x1a\x1f.cplpbv1.UpsertEndpointResponse\"\x03\x90\x02\x02BHZFgithub.com/Sh00ty/cloud-nlb/control-plane/pkg/protobuf/cplpbv1;cplpbv1b\x06proto3"

var (
	file_api_proto_cplpbv1_control_plane_proto_rawDescOnce sync.Once
	file_api_proto_cplpbv1_control_plane_proto_rawDescData []byte
)

func file_api_proto_cplpbv1_control_plane_proto_rawDescGZIP() []byte {
	file_api_proto_cplpbv1_control_plane_proto_rawDescOnce.Do(func() {
		file_api_proto_cplpbv1_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cplpbv1_control_plane_proto_rawDesc), len(file_api_proto_cplpbv1_control_plane_proto_rawDesc)))
	})
	return file_api_proto_cplpbv1_control_plane_proto_rawDescData
}

var file_api_proto_cplpbv1_control_plane_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_proto_cplpbv1_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_cplpbv1_control_plane_proto_goTypes = []any{
	(Protocol)(0),                         // 0: cplpbv1.Protocol
	(DataPlaneHealth)(0),                  // 1: cplpbv1.DataPlaneHealth
	(ResponseCode)(0),                     // 2: cplpbv1.ResponseCode
	(EndpointOperationType)(0),            // 3: cplpbv1.EndpointOperationType
	(*TargetGroupID)(nil),                 // 4: cplpbv1.TargetGroupID
	(*DataPlaneID)(nil),                   // 5: cplpbv1.DataPlaneID
	(*DataPlaneAssignmentRequest)(nil),    // 6: cplpbv1.DataPlaneAssignmentRequest
	(*TargetGroupStatus)(nil),             // 7: cplpbv1.TargetGroupStatus
	(*DataPlaneAssignmentResponse)(nil),   // 8: cplpbv1.DataPlaneAssignmentResponse
	(*TargetGroupAssignment)(nil),         // 9: cplpbv1.TargetGroupAssignment
	(*EndpointsSnapshot)(nil),             // 10: cplpbv1.EndpointsSnapshot
	(*EndpointChangelogEntry)(nil),        // 11: cplpbv1.EndpointChangelogEntry
	(*Endpoint)(nil),                      // 12: cplpbv1.Endpoint
	(*UpsertTargetGroupSpecRequest)(nil),  // 13: cplpbv1.UpsertTargetGroupSpecRequest
	(*TargetGroupSpec)(nil),               // 14: cplpbv1.TargetGroupSpec
	(*HealthCheckConfig)(nil),             // 15: cplpbv1.HealthCheckConfig
	(*UpsertTargetGroupSpecResponse)(nil), // 16: cplpbv1.UpsertTargetGroupSpecResponse
	(*UpsertEndpointRequest)(nil),         // 17: cplpbv1.UpsertEndpointRequest
	(*UpsertEndpointResponse)(nil),        // 18: cplpbv1.UpsertEndpointResponse
	nil,                                   // 19: cplpbv1.DataPlaneAssignmentRequest.TargetGroupsStatusEntry
}
var file_api_proto_cplpbv1_control_plane_proto_depIdxs = []int32{
	5,  // 0: cplpbv1.DataPlaneAssignmentRequest.node_id:type_name -> cplpbv1.DataPlaneID
	19, // 1: cplpbv1.DataPlaneAssignmentRequest.target_groups_status:type_name -> cplpbv1.DataPlaneAssignmentRequest.TargetGroupsStatusEntry
	9,  // 2: cplpbv1.DataPlaneAssignmentResponse.added:type_name -> cplpbv1.TargetGroupAssignment
	9,  // 3: cplpbv1.DataPlaneAssignmentResponse.updated:type_name -> cplpbv1.TargetGroupAssignment
	4,  // 4: cplpbv1.DataPlaneAssignmentResponse.removed:type_name -> cplpbv1.TargetGroupID
	2,  // 5: cplpbv1.DataPlaneAssignmentResponse.response_code:type_name -> cplpbv1.ResponseCode
	4,  // 6: cplpbv1.TargetGroupAssignment.id:type_name -> cplpbv1.TargetGroupID
	14, // 7: cplpbv1.TargetGroupAssignment.spec:type_name -> cplpbv1.TargetGroupSpec
	10, // 8: cplpbv1.TargetGroupAssignment.snapshot:type_name -> cplpbv1.EndpointsSnapshot
	11, // 9: cplpbv1.TargetGroupAssignment.changelog:type_name -> cplpbv1.EndpointChangelogEntry
	12, // 10: cplpbv1.EndpointsSnapshot.endpoints:type_name -> cplpbv1.Endpoint
	12, // 11: cplpbv1.EndpointChangelogEntry.spec:type_name -> cplpbv1.Endpoint
	4,  // 12: cplpbv1.UpsertTargetGroupSpecRequest.id:type_name -> cplpbv1.TargetGroupID
	14, // 13: cplpbv1.UpsertTargetGroupSpecRequest.spec:type_name -> cplpbv1.TargetGroupSpec
	0,  // 14: cplpbv1.TargetGroupSpec.protocol:type_name -> cplpbv1.Protocol
	4,  // 15: cplpbv1.UpsertTargetGroupSpecResponse.id:type_name -> cplpbv1.TargetGroupID
	4,  // 16: cplpbv1.UpsertEndpointRequest.target_group_id:type_name -> cplpbv1.TargetGroupID
	12, // 17: cplpbv1.UpsertEndpointRequest.endpoint:type_name -> cplpbv1.Endpoint
	3,  // 18: cplpbv1.UpsertEndpointRequest.operation:type_name -> cplpbv1.EndpointOperationType
	4,  // 19: cplpbv1.UpsertEndpointResponse.target_group_id:type_name -> cplpbv1.TargetGroupID
	12, // 20: cplpbv1.UpsertEndpointResponse.endpoint:type_name -> cplpbv1.Endpoint
	7,  // 21: cplpbv1.DataPlaneAssignmentRequest.TargetGroupsStatusEntry.value:type_name -> cplpbv1.TargetGroupStatus
	6,  // 22: cplpbv1.ControlPlaneService.StreamDataPlaneAssignments:input_type -> cplpbv1.DataPlaneAssignmentRequest
	13, // 23: cplpbv1.ControlPlaneService.UpsertTargetGroupSpec:input_type -> cplpbv1.UpsertTargetGroupSpecRequest
	17, // 24: cplpbv1.ControlPlaneService.UpsertEndpoint:input_type -> cplpbv1.UpsertEndpointRequest
	8,  // 25: cplpbv1.ControlPlaneService.StreamDataPlaneAssignments:output_type -> cplpbv1.DataPlaneAssignmentResponse
	16, // 26: cplpbv1.ControlPlaneService.UpsertTargetGroupSpec:output_type -> cplpbv1.UpsertTargetGroupSpecResponse
	18, // 27: cplpbv1.ControlPlaneService.UpsertEndpoint:output_type -> cplpbv1.UpsertEndpointResponse
	25, // [25:28] is the sub-list for method output_type
	22, // [22:25] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_proto_cplpbv1_control_plane_proto_init() }
func file_api_proto_cplpbv1_control_plane_proto_init() {
	if File_api_proto_cplpbv1_control_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cplpbv1_control_plane_proto_rawDesc), len(file_api_proto_cplpbv1_control_plane_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cplpbv1_control_plane_proto_goTypes,
		DependencyIndexes: file_api_proto_cplpbv1_control_plane_proto_depIdxs,
		EnumInfos:         file_api_proto_cplpbv1_control_plane_proto_enumTypes,
		MessageInfos:      file_api_proto_cplpbv1_control_plane_proto_msgTypes,
	}.Build()
	File_api_proto_cplpbv1_control_plane_proto = out.File
	file_api_proto_cplpbv1_control_plane_proto_goTypes = nil
	file_api_proto_cplpbv1_control_plane_proto_depIdxs = nil
}
