// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/cplpbv1/control-plane.proto

package cplpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_StreamDataPlaneAssignments_FullMethodName = "/cplpbv1.ControlPlaneService/StreamDataPlaneAssignments"
	ControlPlaneService_UpsertTargetGroupSpec_FullMethodName      = "/cplpbv1.ControlPlaneService/UpsertTargetGroupSpec"
	ControlPlaneService_UpsertEndpoint_FullMethodName             = "/cplpbv1.ControlPlaneService/UpsertEndpoint"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneServiceClient interface {
	// Long-polling запрос для получения изменений размещения
	// Потоковый ответ для поддержки серверных событий:
	// - Первое сообщение: ответ с изменениями или таймаутом
	// - Последующие сообщения: только при наличии изменений (если wait_timeout > 0)
	StreamDataPlaneAssignments(ctx context.Context, in *DataPlaneAssignmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataPlaneAssignmentResponse], error)
	// Создание или обновление таргет-группы
	// Идемпотентная операция: повторный вызов с тем же idempotency_key
	// вернёт тот же результат без побочных эффектов.
	UpsertTargetGroupSpec(ctx context.Context, in *UpsertTargetGroupSpecRequest, opts ...grpc.CallOption) (*UpsertTargetGroupSpecResponse, error)
	// Добавление или удаление эндпоинта из таргет-группы
	// Может вызываться вашим health-check сервисом через Redpanda или напрямую.
	// Для массовых обновлений рекомендуется использовать пакетные операции.
	UpsertEndpoint(ctx context.Context, in *UpsertEndpointRequest, opts ...grpc.CallOption) (*UpsertEndpointResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) StreamDataPlaneAssignments(ctx context.Context, in *DataPlaneAssignmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataPlaneAssignmentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[0], ControlPlaneService_StreamDataPlaneAssignments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataPlaneAssignmentRequest, DataPlaneAssignmentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_StreamDataPlaneAssignmentsClient = grpc.ServerStreamingClient[DataPlaneAssignmentResponse]

func (c *controlPlaneServiceClient) UpsertTargetGroupSpec(ctx context.Context, in *UpsertTargetGroupSpecRequest, opts ...grpc.CallOption) (*UpsertTargetGroupSpecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertTargetGroupSpecResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UpsertTargetGroupSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UpsertEndpoint(ctx context.Context, in *UpsertEndpointRequest, opts ...grpc.CallOption) (*UpsertEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertEndpointResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UpsertEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
type ControlPlaneServiceServer interface {
	// Long-polling запрос для получения изменений размещения
	// Потоковый ответ для поддержки серверных событий:
	// - Первое сообщение: ответ с изменениями или таймаутом
	// - Последующие сообщения: только при наличии изменений (если wait_timeout > 0)
	StreamDataPlaneAssignments(*DataPlaneAssignmentRequest, grpc.ServerStreamingServer[DataPlaneAssignmentResponse]) error
	// Создание или обновление таргет-группы
	// Идемпотентная операция: повторный вызов с тем же idempotency_key
	// вернёт тот же результат без побочных эффектов.
	UpsertTargetGroupSpec(context.Context, *UpsertTargetGroupSpecRequest) (*UpsertTargetGroupSpecResponse, error)
	// Добавление или удаление эндпоинта из таргет-группы
	// Может вызываться вашим health-check сервисом через Redpanda или напрямую.
	// Для массовых обновлений рекомендуется использовать пакетные операции.
	UpsertEndpoint(context.Context, *UpsertEndpointRequest) (*UpsertEndpointResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) StreamDataPlaneAssignments(*DataPlaneAssignmentRequest, grpc.ServerStreamingServer[DataPlaneAssignmentResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamDataPlaneAssignments not implemented")
}
func (UnimplementedControlPlaneServiceServer) UpsertTargetGroupSpec(context.Context, *UpsertTargetGroupSpecRequest) (*UpsertTargetGroupSpecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertTargetGroupSpec not implemented")
}
func (UnimplementedControlPlaneServiceServer) UpsertEndpoint(context.Context, *UpsertEndpointRequest) (*UpsertEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertEndpoint not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_StreamDataPlaneAssignments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataPlaneAssignmentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).StreamDataPlaneAssignments(m, &grpc.GenericServerStream[DataPlaneAssignmentRequest, DataPlaneAssignmentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_StreamDataPlaneAssignmentsServer = grpc.ServerStreamingServer[DataPlaneAssignmentResponse]

func _ControlPlaneService_UpsertTargetGroupSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTargetGroupSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UpsertTargetGroupSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UpsertTargetGroupSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UpsertTargetGroupSpec(ctx, req.(*UpsertTargetGroupSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UpsertEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UpsertEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UpsertEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UpsertEndpoint(ctx, req.(*UpsertEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cplpbv1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertTargetGroupSpec",
			Handler:    _ControlPlaneService_UpsertTargetGroupSpec_Handler,
		},
		{
			MethodName: "UpsertEndpoint",
			Handler:    _ControlPlaneService_UpsertEndpoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDataPlaneAssignments",
			Handler:       _ControlPlaneService_StreamDataPlaneAssignments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/cplpbv1/control-plane.proto",
}
