// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: api/proto/cplpbv1/control-plane.proto

package cplpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneServiceClient interface {
	// Long-polling запрос для получения изменений размещения
	// Потоковый ответ для поддержки серверных событий:
	// - Первое сообщение: ответ с изменениями или таймаутом
	// - Последующие сообщения: только при наличии изменений (если wait_timeout > 0)
	StreamDataPlaneAssignments(ctx context.Context, in *DataPlaneAssignmentRequest, opts ...grpc.CallOption) (ControlPlaneService_StreamDataPlaneAssignmentsClient, error)
	// Создание или обновление таргет-группы
	// Идемпотентная операция: повторный вызов с тем же idempotency_key
	// вернёт тот же результат без побочных эффектов.
	UpsertTargetGroupSpec(ctx context.Context, in *UpsertTargetGroupSpecRequest, opts ...grpc.CallOption) (*UpsertTargetGroupSpecResponse, error)
	// Добавление или удаление эндпоинта из таргет-группы
	// Может вызываться вашим health-check сервисом через Redpanda или напрямую.
	// Для массовых обновлений рекомендуется использовать пакетные операции.
	UpsertEndpoint(ctx context.Context, in *UpsertEndpointRequest, opts ...grpc.CallOption) (*UpsertEndpointResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) StreamDataPlaneAssignments(ctx context.Context, in *DataPlaneAssignmentRequest, opts ...grpc.CallOption) (ControlPlaneService_StreamDataPlaneAssignmentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[0], "/cplpbv1.ControlPlaneService/StreamDataPlaneAssignments", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlPlaneServiceStreamDataPlaneAssignmentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlPlaneService_StreamDataPlaneAssignmentsClient interface {
	Recv() (*DataPlaneAssignmentResponse, error)
	grpc.ClientStream
}

type controlPlaneServiceStreamDataPlaneAssignmentsClient struct {
	grpc.ClientStream
}

func (x *controlPlaneServiceStreamDataPlaneAssignmentsClient) Recv() (*DataPlaneAssignmentResponse, error) {
	m := new(DataPlaneAssignmentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlPlaneServiceClient) UpsertTargetGroupSpec(ctx context.Context, in *UpsertTargetGroupSpecRequest, opts ...grpc.CallOption) (*UpsertTargetGroupSpecResponse, error) {
	out := new(UpsertTargetGroupSpecResponse)
	err := c.cc.Invoke(ctx, "/cplpbv1.ControlPlaneService/UpsertTargetGroupSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UpsertEndpoint(ctx context.Context, in *UpsertEndpointRequest, opts ...grpc.CallOption) (*UpsertEndpointResponse, error) {
	out := new(UpsertEndpointResponse)
	err := c.cc.Invoke(ctx, "/cplpbv1.ControlPlaneService/UpsertEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility
type ControlPlaneServiceServer interface {
	// Long-polling запрос для получения изменений размещения
	// Потоковый ответ для поддержки серверных событий:
	// - Первое сообщение: ответ с изменениями или таймаутом
	// - Последующие сообщения: только при наличии изменений (если wait_timeout > 0)
	StreamDataPlaneAssignments(*DataPlaneAssignmentRequest, ControlPlaneService_StreamDataPlaneAssignmentsServer) error
	// Создание или обновление таргет-группы
	// Идемпотентная операция: повторный вызов с тем же idempotency_key
	// вернёт тот же результат без побочных эффектов.
	UpsertTargetGroupSpec(context.Context, *UpsertTargetGroupSpecRequest) (*UpsertTargetGroupSpecResponse, error)
	// Добавление или удаление эндпоинта из таргет-группы
	// Может вызываться вашим health-check сервисом через Redpanda или напрямую.
	// Для массовых обновлений рекомендуется использовать пакетные операции.
	UpsertEndpoint(context.Context, *UpsertEndpointRequest) (*UpsertEndpointResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have forward compatible implementations.
type UnimplementedControlPlaneServiceServer struct {
}

func (UnimplementedControlPlaneServiceServer) StreamDataPlaneAssignments(*DataPlaneAssignmentRequest, ControlPlaneService_StreamDataPlaneAssignmentsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamDataPlaneAssignments not implemented")
}
func (UnimplementedControlPlaneServiceServer) UpsertTargetGroupSpec(context.Context, *UpsertTargetGroupSpecRequest) (*UpsertTargetGroupSpecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertTargetGroupSpec not implemented")
}
func (UnimplementedControlPlaneServiceServer) UpsertEndpoint(context.Context, *UpsertEndpointRequest) (*UpsertEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertEndpoint not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_StreamDataPlaneAssignments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataPlaneAssignmentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).StreamDataPlaneAssignments(m, &controlPlaneServiceStreamDataPlaneAssignmentsServer{stream})
}

type ControlPlaneService_StreamDataPlaneAssignmentsServer interface {
	Send(*DataPlaneAssignmentResponse) error
	grpc.ServerStream
}

type controlPlaneServiceStreamDataPlaneAssignmentsServer struct {
	grpc.ServerStream
}

func (x *controlPlaneServiceStreamDataPlaneAssignmentsServer) Send(m *DataPlaneAssignmentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlPlaneService_UpsertTargetGroupSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTargetGroupSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UpsertTargetGroupSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cplpbv1.ControlPlaneService/UpsertTargetGroupSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UpsertTargetGroupSpec(ctx, req.(*UpsertTargetGroupSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UpsertEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UpsertEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cplpbv1.ControlPlaneService/UpsertEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UpsertEndpoint(ctx, req.(*UpsertEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cplpbv1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertTargetGroupSpec",
			Handler:    _ControlPlaneService_UpsertTargetGroupSpec_Handler,
		},
		{
			MethodName: "UpsertEndpoint",
			Handler:    _ControlPlaneService_UpsertEndpoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDataPlaneAssignments",
			Handler:       _ControlPlaneService_StreamDataPlaneAssignments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/cplpbv1/control-plane.proto",
}
