{
 "title": "Health Check Processor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "percentile", "query": "0.5, 0.9, 0.95, 0.99" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(health_check_node_executor_channel_buffer_usage,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "All Instances Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Checks By All Cluster Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(health_check_node_scheduler_heap_size{job=\"kubernetes-pods\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "[ALL] Membership Events Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(health_check_node_coordinator_membership_events_total{job=\"kubernetes-pods\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "[ALL] Coordinator — Target Events CDC Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(health_check_node_coordinator_target_events_total{job=\"kubernetes-pods\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Invocation Delay Latency ($percentile%%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile:raw}, sum by (le) (rate(health_check_node_scheduler_invocation_delay_seconds_bucket{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "P$percentile"
    }
   ]
  },
  {
   "title": "Sharder — Vshards Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (health_check_node_sharder_my_vshards_count{job=\"kubernetes-pods\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sender — Send Success Ratio %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(sum by (pod) (increase(health_check_node_sender_send_duration_seconds_count{job=\"kubernetes-pods\", success=\"true\"}[$__rate_interval])), 1) / clamp_min(sum by (pod) (increase(health_check_node_sender_send_duration_seconds_count{job=\"kubernetes-pods\"}[$__rate_interval])), 1) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Coordinator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Coordinator — Fetch Targets Latency (${percentile}%%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile:raw}, sum(rate(health_check_node_coordinator_fetch_targets_duration_seconds_bucket{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval])) by (pod, le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fetch Targets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(health_check_node_coordinator_fetch_targets_duration_seconds_count{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator — Fetched Targets per Fetch (среднее по инстансам)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(health_check_node_coordinator_fetched_targets_total{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval])) / clamp_min(sum by (pod) (rate(health_check_node_coordinator_fetch_targets_duration_seconds_count{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval])), 1)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator — Target Events CDC Count By Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod,operation) (increase(health_check_node_coordinator_target_events_total{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}.{{operation}}"
    }
   ]
  },
  {
   "title": "Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Channel Buffer Usage (по инстансам)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * sum by (pod) (health_check_node_executor_channel_buffer_usage{job=\"kubernetes-pods\", pod=~\"$pod\"})\n/\nsum by (pod) (health_check_node_executor_channel_buffer_capacity{job=\"kubernetes-pods\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Executor — Task Duration Latency ($percentile%%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by (le, pod) (rate(health_check_node_executor_task_duration_seconds_bucket{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Task Execution Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(health_check_node_executor_task_duration_seconds_count{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Task Status Changes Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(health_check_node_executor_task_duration_seconds_count{job=\"kubernetes-pods\", changed=\"true\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Status Sender",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sender — Send Success Ratio %",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min(sum by (pod) (increase(health_check_node_sender_send_duration_seconds_count{job=\"kubernetes-pods\", success=\"true\", pod=~\"$pod\"}[$__rate_interval])), 1) / clamp_min(sum by (pod) (increase(health_check_node_sender_send_duration_seconds_count{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval])), 1) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sender — Unsent Resync Rate ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (health_check_node_sender_unsent_resync_duration_seconds_count{job=\"kubernetes-pods\", pod=~\"$pod\"}) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sender — Send Duration Latency ($percentile%%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by (le, pod, success) (rate(health_check_node_sender_send_duration_seconds_bucket{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "{{pod}} success={{success}}"
      }
     ]
    },
    {
     "title": "Sender — Send Rate (по success и инстансам)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (success, pod) (rate(health_check_node_sender_send_duration_seconds_count{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}.{{success}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Check Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Schedule Rate ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(health_check_node_scheduler_schedule_duration_seconds_count{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Schedule Duration Latency ($percentile%%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by (le, pod) (rate(health_check_node_scheduler_schedule_duration_seconds_bucket{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Invocation Delay Latency ($percentile%%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by (le, pod) (rate(health_check_node_scheduler_invocation_delay_seconds_bucket{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Scheduler Checks Heap Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (health_check_node_scheduler_heap_size{job=\"kubernetes-pods\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Scheduler — Empty Loop Iterations Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(health_check_node_scheduler_empty_loop_iterations_total{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Scheduler Operations Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(health_check_node_scheduler_adds_total{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}.add"
      },
      {
       "expr": "sum by (pod) (rate(health_check_node_scheduler_removes_total{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}.remove"
      }
     ]
    }
   ]
  },
  {
   "title": "Membership",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Membership Events Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (type, pod) (rate(health_check_node_coordinator_membership_events_total{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{type}}.{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sharder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sharder — My Vshards Count (по инстансам)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (health_check_node_sharder_my_vshards_count{job=\"kubernetes-pods\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      },
      { "expr": "300", "legendFormat": "capacity" }
     ]
    },
    {
     "title": "Sharder — Acquired/Dropped Vshards on Rebalance Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(health_check_node_sharder_dropped_targets_on_rebalance_total{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}.dropped"
      },
      {
       "expr": "sum by (pod) (increase(health_check_node_sharder_acquired_vshards_on_rebalance_total{job=\"kubernetes-pods\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}.acquired"
      }
     ]
    }
   ]
  }
 ]
}