apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
  namespace: cloud-nlb
  labels:
    app: test-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: test-server
        image: testsrv:dev
        imagePullPolicy: IfNotPresent
        ports:
        - name: metrics
          containerPort: 8081
          protocol: TCP
        - name: lb-hc
          containerPort: 8090
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        env:
          - name: METRICS_ADDR
            value: "0.0.0.0:8081"
          - name: HC_PORT
            value: "8090"
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 5
          periodSeconds: 5