global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kubernetes-pods"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9100"]
        labels:
          instance: "hc-worker-0"
          app: "hc-worker"
          namespace: "cloud-nlb"
          pod: "hc-worker-0"

      - targets: ["host.docker.internal:9101"]
        labels:
          instance: "nlb-agent-0"
          app: "nlb-agent"
          namespace: "cloud-nlb"
          pod: "nlb-agent-0"

      - targets: ["host.docker.internal:9102"]
        labels:
          instance: "control-plane-reconciler-0"
          app: "control-plane-reconciler"
          namespace: "cloud-nlb"
          pod: "control-plane-reconciler-0"
      - targets: ["host.docker.internal:9103"]
        labels:
          instance: "control-plane-apiserver-0"
          app: "control-plane-apiserver"
          namespace: "cloud-nlb"
          pod: "control-plane-apiserver-0"