apiVersion: v1
kind: ConfigMap
metadata:
  name: nlb-agent-config
  namespace: cloud-nlb
data:
  LOGGER_LEVEL: "INFO"
  LOGGER_USE_PRETTY: "false"
  DEBUG: "true"
  NEED_PROBES: "true"

  TTL_UNTIL_NODE_DEATH: "3s"
  PERSISTENT_STORAGE_PATH_TEMPLATE: "/tmp/nlb-agent/dpl-%s"

  MAX_RECONCILE_ATTEMPTS: "5"
  FORCE_RECONCILE_INTERVAL: "20s"
  RECONCILER_CONCURRENCY: "6"

  CONTROL_PLANE_ADDR: "control-plane-apiserver.local:30080"
  CONTROL_PLANE_LONG_POLL_DURATION: "20s"

  ENDPOINTS_SERVICE_ADDR: "hc-server.local:30080"
  ENDPOINT_STATUSES_RESYNC_INTERVAL: "1m"

  QUEUE_ADDR: "192.168.5.2:19092"
  QUEUE_ENDPOINT_STATUSES_TOPIC: "dbserver1.public.target_statuses"

  VPP_MODE: "USER_SPACE_TEST"

  ETCD_ENDPOINT: "192.168.5.2:2379"
  METRICS_ADDR: "0.0.0.0:8081"