// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/hcpbv1/lbhealth.proto

package hcpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthCheckService_CreateSettings_FullMethodName      = "/healthcheck.v1.HealthCheckService/CreateSettings"
	HealthCheckService_AddEndpoints_FullMethodName        = "/healthcheck.v1.HealthCheckService/AddEndpoints"
	HealthCheckService_RemoveEndpoints_FullMethodName     = "/healthcheck.v1.HealthCheckService/RemoveEndpoints"
	HealthCheckService_GetEndpointStatuses_FullMethodName = "/healthcheck.v1.HealthCheckService/GetEndpointStatuses"
)

// HealthCheckServiceClient is the client API for HealthCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckServiceClient interface {
	CreateSettings(ctx context.Context, in *CreateSettingsRequest, opts ...grpc.CallOption) (*CreateSettingsResponse, error)
	AddEndpoints(ctx context.Context, in *AddEndpointsRequest, opts ...grpc.CallOption) (*AddEndpointsResponse, error)
	RemoveEndpoints(ctx context.Context, in *RemoveEndpointsRequest, opts ...grpc.CallOption) (*RemoveEndpointsResponse, error)
	GetEndpointStatuses(ctx context.Context, in *GetEndpointStatusesRequest, opts ...grpc.CallOption) (*GetEndpointStatusesResponse, error)
}

type healthCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckServiceClient(cc grpc.ClientConnInterface) HealthCheckServiceClient {
	return &healthCheckServiceClient{cc}
}

func (c *healthCheckServiceClient) CreateSettings(ctx context.Context, in *CreateSettingsRequest, opts ...grpc.CallOption) (*CreateSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSettingsResponse)
	err := c.cc.Invoke(ctx, HealthCheckService_CreateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthCheckServiceClient) AddEndpoints(ctx context.Context, in *AddEndpointsRequest, opts ...grpc.CallOption) (*AddEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEndpointsResponse)
	err := c.cc.Invoke(ctx, HealthCheckService_AddEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthCheckServiceClient) RemoveEndpoints(ctx context.Context, in *RemoveEndpointsRequest, opts ...grpc.CallOption) (*RemoveEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveEndpointsResponse)
	err := c.cc.Invoke(ctx, HealthCheckService_RemoveEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthCheckServiceClient) GetEndpointStatuses(ctx context.Context, in *GetEndpointStatusesRequest, opts ...grpc.CallOption) (*GetEndpointStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEndpointStatusesResponse)
	err := c.cc.Invoke(ctx, HealthCheckService_GetEndpointStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckServiceServer is the server API for HealthCheckService service.
// All implementations must embed UnimplementedHealthCheckServiceServer
// for forward compatibility.
type HealthCheckServiceServer interface {
	CreateSettings(context.Context, *CreateSettingsRequest) (*CreateSettingsResponse, error)
	AddEndpoints(context.Context, *AddEndpointsRequest) (*AddEndpointsResponse, error)
	RemoveEndpoints(context.Context, *RemoveEndpointsRequest) (*RemoveEndpointsResponse, error)
	GetEndpointStatuses(context.Context, *GetEndpointStatusesRequest) (*GetEndpointStatusesResponse, error)
	mustEmbedUnimplementedHealthCheckServiceServer()
}

// UnimplementedHealthCheckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthCheckServiceServer struct{}

func (UnimplementedHealthCheckServiceServer) CreateSettings(context.Context, *CreateSettingsRequest) (*CreateSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSettings not implemented")
}
func (UnimplementedHealthCheckServiceServer) AddEndpoints(context.Context, *AddEndpointsRequest) (*AddEndpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEndpoints not implemented")
}
func (UnimplementedHealthCheckServiceServer) RemoveEndpoints(context.Context, *RemoveEndpointsRequest) (*RemoveEndpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveEndpoints not implemented")
}
func (UnimplementedHealthCheckServiceServer) GetEndpointStatuses(context.Context, *GetEndpointStatusesRequest) (*GetEndpointStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEndpointStatuses not implemented")
}
func (UnimplementedHealthCheckServiceServer) mustEmbedUnimplementedHealthCheckServiceServer() {}
func (UnimplementedHealthCheckServiceServer) testEmbeddedByValue()                            {}

// UnsafeHealthCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckServiceServer will
// result in compilation errors.
type UnsafeHealthCheckServiceServer interface {
	mustEmbedUnimplementedHealthCheckServiceServer()
}

func RegisterHealthCheckServiceServer(s grpc.ServiceRegistrar, srv HealthCheckServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthCheckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthCheckService_ServiceDesc, srv)
}

func _HealthCheckService_CreateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).CreateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthCheckService_CreateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).CreateSettings(ctx, req.(*CreateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthCheckService_AddEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).AddEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthCheckService_AddEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).AddEndpoints(ctx, req.(*AddEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthCheckService_RemoveEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).RemoveEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthCheckService_RemoveEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).RemoveEndpoints(ctx, req.(*RemoveEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthCheckService_GetEndpointStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEndpointStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).GetEndpointStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthCheckService_GetEndpointStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).GetEndpointStatuses(ctx, req.(*GetEndpointStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthCheckService_ServiceDesc is the grpc.ServiceDesc for HealthCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "healthcheck.v1.HealthCheckService",
	HandlerType: (*HealthCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSettings",
			Handler:    _HealthCheckService_CreateSettings_Handler,
		},
		{
			MethodName: "AddEndpoints",
			Handler:    _HealthCheckService_AddEndpoints_Handler,
		},
		{
			MethodName: "RemoveEndpoints",
			Handler:    _HealthCheckService_RemoveEndpoints_Handler,
		},
		{
			MethodName: "GetEndpointStatuses",
			Handler:    _HealthCheckService_GetEndpointStatuses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/hcpbv1/lbhealth.proto",
}
