// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/hcpbv1/lbhealth.proto

package hcpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StrategyType int32

const (
	StrategyType_STRATEGY_TYPE_UNSPECIFIED StrategyType = 0
	StrategyType_STRATEGY_TYPE_MOCK        StrategyType = 1
	StrategyType_STRATEGY_TYPE_HTTP        StrategyType = 2
	StrategyType_STRATEGY_TYPE_TCP         StrategyType = 3
)

// Enum value maps for StrategyType.
var (
	StrategyType_name = map[int32]string{
		0: "STRATEGY_TYPE_UNSPECIFIED",
		1: "STRATEGY_TYPE_MOCK",
		2: "STRATEGY_TYPE_HTTP",
		3: "STRATEGY_TYPE_TCP",
	}
	StrategyType_value = map[string]int32{
		"STRATEGY_TYPE_UNSPECIFIED": 0,
		"STRATEGY_TYPE_MOCK":        1,
		"STRATEGY_TYPE_HTTP":        2,
		"STRATEGY_TYPE_TCP":         3,
	}
)

func (x StrategyType) Enum() *StrategyType {
	p := new(StrategyType)
	*p = x
	return p
}

func (x StrategyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StrategyType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_hcpbv1_lbhealth_proto_enumTypes[0].Descriptor()
}

func (StrategyType) Type() protoreflect.EnumType {
	return &file_api_proto_hcpbv1_lbhealth_proto_enumTypes[0]
}

func (x StrategyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StrategyType.Descriptor instead.
func (StrategyType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{0}
}

type Settings struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetGroup            string                 `protobuf:"bytes,1,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	Interval               *durationpb.Duration   `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	SuccessBeforePassing   uint32                 `protobuf:"varint,3,opt,name=success_before_passing,json=successBeforePassing,proto3" json:"success_before_passing,omitempty"`
	FailuresBeforeCritical uint32                 `protobuf:"varint,4,opt,name=failures_before_critical,json=failuresBeforeCritical,proto3" json:"failures_before_critical,omitempty"`
	InitialState           bool                   `protobuf:"varint,5,opt,name=initial_state,json=initialState,proto3" json:"initial_state,omitempty"`
	Strategy               StrategyType           `protobuf:"varint,6,opt,name=strategy,proto3,enum=healthcheck.v1.StrategyType" json:"strategy,omitempty"`
	StrategySettings       *structpb.Struct       `protobuf:"bytes,7,opt,name=strategy_settings,json=strategySettings,proto3" json:"strategy_settings,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *Settings) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *Settings) GetSuccessBeforePassing() uint32 {
	if x != nil {
		return x.SuccessBeforePassing
	}
	return 0
}

func (x *Settings) GetFailuresBeforeCritical() uint32 {
	if x != nil {
		return x.FailuresBeforeCritical
	}
	return 0
}

func (x *Settings) GetInitialState() bool {
	if x != nil {
		return x.InitialState
	}
	return false
}

func (x *Settings) GetStrategy() StrategyType {
	if x != nil {
		return x.Strategy
	}
	return StrategyType_STRATEGY_TYPE_UNSPECIFIED
}

func (x *Settings) GetStrategySettings() *structpb.Struct {
	if x != nil {
		return x.StrategySettings
	}
	return nil
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealIp        string                 `protobuf:"bytes,1,opt,name=real_ip,json=realIp,proto3" json:"real_ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{1}
}

func (x *Endpoint) GetRealIp() string {
	if x != nil {
		return x.RealIp
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type EndpointStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealIp        string                 `protobuf:"bytes,1,opt,name=real_ip,json=realIp,proto3" json:"real_ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	TargetGroup   string                 `protobuf:"bytes,3,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	IsHealthy     bool                   `protobuf:"varint,4,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointStatus) Reset() {
	*x = EndpointStatus{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointStatus) ProtoMessage() {}

func (x *EndpointStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointStatus.ProtoReflect.Descriptor instead.
func (*EndpointStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointStatus) GetRealIp() string {
	if x != nil {
		return x.RealIp
	}
	return ""
}

func (x *EndpointStatus) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EndpointStatus) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *EndpointStatus) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *EndpointStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *EndpointStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSettingsRequest) Reset() {
	*x = CreateSettingsRequest{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSettingsRequest) ProtoMessage() {}

func (x *CreateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSettingsRequest.ProtoReflect.Descriptor instead.
func (*CreateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSettingsRequest) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CreateSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSettingsResponse) Reset() {
	*x = CreateSettingsResponse{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSettingsResponse) ProtoMessage() {}

func (x *CreateSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSettingsResponse.ProtoReflect.Descriptor instead.
func (*CreateSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSettingsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSettingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetGroup   string                 `protobuf:"bytes,1,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEndpointsRequest) Reset() {
	*x = AddEndpointsRequest{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEndpointsRequest) ProtoMessage() {}

func (x *AddEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEndpointsRequest.ProtoReflect.Descriptor instead.
func (*AddEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{5}
}

func (x *AddEndpointsRequest) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *AddEndpointsRequest) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type AddEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddedCount    uint32                 `protobuf:"varint,1,opt,name=added_count,json=addedCount,proto3" json:"added_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEndpointsResponse) Reset() {
	*x = AddEndpointsResponse{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEndpointsResponse) ProtoMessage() {}

func (x *AddEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEndpointsResponse.ProtoReflect.Descriptor instead.
func (*AddEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{6}
}

func (x *AddEndpointsResponse) GetAddedCount() uint32 {
	if x != nil {
		return x.AddedCount
	}
	return 0
}

type RemoveEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetGroup   string                 `protobuf:"bytes,1,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEndpointsRequest) Reset() {
	*x = RemoveEndpointsRequest{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEndpointsRequest) ProtoMessage() {}

func (x *RemoveEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEndpointsRequest.ProtoReflect.Descriptor instead.
func (*RemoveEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveEndpointsRequest) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *RemoveEndpointsRequest) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type RemoveEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemovedCount  uint32                 `protobuf:"varint,1,opt,name=removed_count,json=removedCount,proto3" json:"removed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEndpointsResponse) Reset() {
	*x = RemoveEndpointsResponse{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEndpointsResponse) ProtoMessage() {}

func (x *RemoveEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEndpointsResponse.ProtoReflect.Descriptor instead.
func (*RemoveEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveEndpointsResponse) GetRemovedCount() uint32 {
	if x != nil {
		return x.RemovedCount
	}
	return 0
}

type GetEndpointStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetGroup   string                 `protobuf:"bytes,1,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointStatusesRequest) Reset() {
	*x = GetEndpointStatusesRequest{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointStatusesRequest) ProtoMessage() {}

func (x *GetEndpointStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointStatusesRequest.ProtoReflect.Descriptor instead.
func (*GetEndpointStatusesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{9}
}

func (x *GetEndpointStatusesRequest) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

type GetEndpointStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*EndpointStatus      `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointStatusesResponse) Reset() {
	*x = GetEndpointStatusesResponse{}
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointStatusesResponse) ProtoMessage() {}

func (x *GetEndpointStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hcpbv1_lbhealth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointStatusesResponse.ProtoReflect.Descriptor instead.
func (*GetEndpointStatusesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP(), []int{10}
}

func (x *GetEndpointStatusesResponse) GetStatuses() []*EndpointStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_api_proto_hcpbv1_lbhealth_proto protoreflect.FileDescriptor

const file_api_proto_hcpbv1_lbhealth_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/hcpbv1/lbhealth.proto\x12\x0ehealthcheck.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf9\x02\n" +
	"\bSettings\x12!\n" +
	"\ftarget_group\x18\x01 \x01(\tR\vtargetGroup\x125\n" +
	"\binterval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\binterval\x124\n" +
	"\x16success_before_passing\x18\x03 \x01(\rR\x14successBeforePassing\x128\n" +
	"\x18failures_before_critical\x18\x04 \x01(\rR\x16failuresBeforeCritical\x12#\n" +
	"\rinitial_state\x18\x05 \x01(\bR\finitialState\x128\n" +
	"\bstrategy\x18\x06 \x01(\x0e2\x1c.healthcheck.v1.StrategyTypeR\bstrategy\x12D\n" +
	"\x11strategy_settings\x18\a \x01(\v2\x17.google.protobuf.StructR\x10strategySettings\"7\n" +
	"\bEndpoint\x12\x17\n" +
	"\areal_ip\x18\x01 \x01(\tR\x06realIp\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\xd9\x01\n" +
	"\x0eEndpointStatus\x12\x17\n" +
	"\areal_ip\x18\x01 \x01(\tR\x06realIp\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12!\n" +
	"\ftarget_group\x18\x03 \x01(\tR\vtargetGroup\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x04 \x01(\bR\tisHealthy\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"M\n" +
	"\x15CreateSettingsRequest\x124\n" +
	"\bsettings\x18\x01 \x01(\v2\x18.healthcheck.v1.SettingsR\bsettings\"L\n" +
	"\x16CreateSettingsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\x13AddEndpointsRequest\x12!\n" +
	"\ftarget_group\x18\x01 \x01(\tR\vtargetGroup\x126\n" +
	"\tendpoints\x18\x02 \x03(\v2\x18.healthcheck.v1.EndpointR\tendpoints\"7\n" +
	"\x14AddEndpointsResponse\x12\x1f\n" +
	"\vadded_count\x18\x01 \x01(\rR\n" +
	"addedCount\"s\n" +
	"\x16RemoveEndpointsRequest\x12!\n" +
	"\ftarget_group\x18\x01 \x01(\tR\vtargetGroup\x126\n" +
	"\tendpoints\x18\x02 \x03(\v2\x18.healthcheck.v1.EndpointR\tendpoints\">\n" +
	"\x17RemoveEndpointsResponse\x12#\n" +
	"\rremoved_count\x18\x01 \x01(\rR\fremovedCount\"?\n" +
	"\x1aGetEndpointStatusesRequest\x12!\n" +
	"\ftarget_group\x18\x01 \x01(\tR\vtargetGroup\"Y\n" +
	"\x1bGetEndpointStatusesResponse\x12:\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1e.healthcheck.v1.EndpointStatusR\bstatuses*t\n" +
	"\fStrategyType\x12\x1d\n" +
	"\x19STRATEGY_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STRATEGY_TYPE_MOCK\x10\x01\x12\x16\n" +
	"\x12STRATEGY_TYPE_HTTP\x10\x02\x12\x15\n" +
	"\x11STRATEGY_TYPE_TCP\x10\x032\xa4\x03\n" +
	"\x12HealthCheckService\x12_\n" +
	"\x0eCreateSettings\x12%.healthcheck.v1.CreateSettingsRequest\x1a&.healthcheck.v1.CreateSettingsResponse\x12Y\n" +
	"\fAddEndpoints\x12#.healthcheck.v1.AddEndpointsRequest\x1a$.healthcheck.v1.AddEndpointsResponse\x12b\n" +
	"\x0fRemoveEndpoints\x12&.healthcheck.v1.RemoveEndpointsRequest\x1a'.healthcheck.v1.RemoveEndpointsResponse\x12n\n" +
	"\x13GetEndpointStatuses\x12*.healthcheck.v1.GetEndpointStatusesRequest\x1a+.healthcheck.v1.GetEndpointStatusesResponseBDZBgithub.com/Sh00ty/cloud-nlb/healthcheck/pkg/protobuf/hcpbv1;hcpbv1b\x06proto3"

var (
	file_api_proto_hcpbv1_lbhealth_proto_rawDescOnce sync.Once
	file_api_proto_hcpbv1_lbhealth_proto_rawDescData []byte
)

func file_api_proto_hcpbv1_lbhealth_proto_rawDescGZIP() []byte {
	file_api_proto_hcpbv1_lbhealth_proto_rawDescOnce.Do(func() {
		file_api_proto_hcpbv1_lbhealth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_hcpbv1_lbhealth_proto_rawDesc), len(file_api_proto_hcpbv1_lbhealth_proto_rawDesc)))
	})
	return file_api_proto_hcpbv1_lbhealth_proto_rawDescData
}

var file_api_proto_hcpbv1_lbhealth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_hcpbv1_lbhealth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_hcpbv1_lbhealth_proto_goTypes = []any{
	(StrategyType)(0),                   // 0: healthcheck.v1.StrategyType
	(*Settings)(nil),                    // 1: healthcheck.v1.Settings
	(*Endpoint)(nil),                    // 2: healthcheck.v1.Endpoint
	(*EndpointStatus)(nil),              // 3: healthcheck.v1.EndpointStatus
	(*CreateSettingsRequest)(nil),       // 4: healthcheck.v1.CreateSettingsRequest
	(*CreateSettingsResponse)(nil),      // 5: healthcheck.v1.CreateSettingsResponse
	(*AddEndpointsRequest)(nil),         // 6: healthcheck.v1.AddEndpointsRequest
	(*AddEndpointsResponse)(nil),        // 7: healthcheck.v1.AddEndpointsResponse
	(*RemoveEndpointsRequest)(nil),      // 8: healthcheck.v1.RemoveEndpointsRequest
	(*RemoveEndpointsResponse)(nil),     // 9: healthcheck.v1.RemoveEndpointsResponse
	(*GetEndpointStatusesRequest)(nil),  // 10: healthcheck.v1.GetEndpointStatusesRequest
	(*GetEndpointStatusesResponse)(nil), // 11: healthcheck.v1.GetEndpointStatusesResponse
	(*durationpb.Duration)(nil),         // 12: google.protobuf.Duration
	(*structpb.Struct)(nil),             // 13: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
}
var file_api_proto_hcpbv1_lbhealth_proto_depIdxs = []int32{
	12, // 0: healthcheck.v1.Settings.interval:type_name -> google.protobuf.Duration
	0,  // 1: healthcheck.v1.Settings.strategy:type_name -> healthcheck.v1.StrategyType
	13, // 2: healthcheck.v1.Settings.strategy_settings:type_name -> google.protobuf.Struct
	14, // 3: healthcheck.v1.EndpointStatus.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: healthcheck.v1.CreateSettingsRequest.settings:type_name -> healthcheck.v1.Settings
	2,  // 5: healthcheck.v1.AddEndpointsRequest.endpoints:type_name -> healthcheck.v1.Endpoint
	2,  // 6: healthcheck.v1.RemoveEndpointsRequest.endpoints:type_name -> healthcheck.v1.Endpoint
	3,  // 7: healthcheck.v1.GetEndpointStatusesResponse.statuses:type_name -> healthcheck.v1.EndpointStatus
	4,  // 8: healthcheck.v1.HealthCheckService.CreateSettings:input_type -> healthcheck.v1.CreateSettingsRequest
	6,  // 9: healthcheck.v1.HealthCheckService.AddEndpoints:input_type -> healthcheck.v1.AddEndpointsRequest
	8,  // 10: healthcheck.v1.HealthCheckService.RemoveEndpoints:input_type -> healthcheck.v1.RemoveEndpointsRequest
	10, // 11: healthcheck.v1.HealthCheckService.GetEndpointStatuses:input_type -> healthcheck.v1.GetEndpointStatusesRequest
	5,  // 12: healthcheck.v1.HealthCheckService.CreateSettings:output_type -> healthcheck.v1.CreateSettingsResponse
	7,  // 13: healthcheck.v1.HealthCheckService.AddEndpoints:output_type -> healthcheck.v1.AddEndpointsResponse
	9,  // 14: healthcheck.v1.HealthCheckService.RemoveEndpoints:output_type -> healthcheck.v1.RemoveEndpointsResponse
	11, // 15: healthcheck.v1.HealthCheckService.GetEndpointStatuses:output_type -> healthcheck.v1.GetEndpointStatusesResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_hcpbv1_lbhealth_proto_init() }
func file_api_proto_hcpbv1_lbhealth_proto_init() {
	if File_api_proto_hcpbv1_lbhealth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_hcpbv1_lbhealth_proto_rawDesc), len(file_api_proto_hcpbv1_lbhealth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_hcpbv1_lbhealth_proto_goTypes,
		DependencyIndexes: file_api_proto_hcpbv1_lbhealth_proto_depIdxs,
		EnumInfos:         file_api_proto_hcpbv1_lbhealth_proto_enumTypes,
		MessageInfos:      file_api_proto_hcpbv1_lbhealth_proto_msgTypes,
	}.Build()
	File_api_proto_hcpbv1_lbhealth_proto = out.File
	file_api_proto_hcpbv1_lbhealth_proto_goTypes = nil
	file_api_proto_hcpbv1_lbhealth_proto_depIdxs = nil
}
